@Library(['github.com/indigo-dc/jenkins-pipeline-library@release/2.1.0']) _

def projectConfig

pipeline {
    agent any

    stages {
        {% for config_data in config_data_list %}
        stage('SQA baseline criterion: {{ config_data.data_json.sqa_criteria |list |first |e }}') {
            steps {
                script {
                    projectConfig = pipelineConfig(
                        configFile: '{{ config_data.file_name }}',
                        scmConfigs: [ localBranch: true ]
                    )
                    buildStages(projectConfig)
                }
            }
            post {
                cleanup {
                    cleanWs()
                }
            }
        }
        {% endfor %}
    }
}
