# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.badge_recipient import BadgeRecipient
from openapi_server import util


class Badge(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, open_badge_id: str=None, created_at: datetime=None, created_by: str=None, badge_class: str=None, issuer: str=None, image: str=None, recipient: BadgeRecipient=None, issued_on: datetime=None):
        """Badge - a model defined in OpenAPI

        :param open_badge_id: The open_badge_id of this Badge.
        :param created_at: The created_at of this Badge.
        :param created_by: The created_by of this Badge.
        :param badge_class: The badge_class of this Badge.
        :param issuer: The issuer of this Badge.
        :param image: The image of this Badge.
        :param recipient: The recipient of this Badge.
        :param issued_on: The issued_on of this Badge.
        """
        self.openapi_types = {
            'open_badge_id': str,
            'created_at': datetime,
            'created_by': str,
            'badge_class': str,
            'issuer': str,
            'image': str,
            'recipient': BadgeRecipient,
            'issued_on': datetime
        }

        self.attribute_map = {
            'open_badge_id': 'openBadgeID',
            'created_at': 'createdAt',
            'created_by': 'createdBy',
            'badge_class': 'badgeClass',
            'issuer': 'issuer',
            'image': 'image',
            'recipient': 'recipient',
            'issued_on': 'issuedOn'
        }

        self._open_badge_id = open_badge_id
        self._created_at = created_at
        self._created_by = created_by
        self._badge_class = badge_class
        self._issuer = issuer
        self._image = image
        self._recipient = recipient
        self._issued_on = issued_on

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Badge':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Badge of this Badge.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def open_badge_id(self):
        """Gets the open_badge_id of this Badge.


        :return: The open_badge_id of this Badge.
        :rtype: str
        """
        return self._open_badge_id

    @open_badge_id.setter
    def open_badge_id(self, open_badge_id):
        """Sets the open_badge_id of this Badge.


        :param open_badge_id: The open_badge_id of this Badge.
        :type open_badge_id: str
        """

        self._open_badge_id = open_badge_id

    @property
    def created_at(self):
        """Gets the created_at of this Badge.


        :return: The created_at of this Badge.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Badge.


        :param created_at: The created_at of this Badge.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def created_by(self):
        """Gets the created_by of this Badge.


        :return: The created_by of this Badge.
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this Badge.


        :param created_by: The created_by of this Badge.
        :type created_by: str
        """

        self._created_by = created_by

    @property
    def badge_class(self):
        """Gets the badge_class of this Badge.


        :return: The badge_class of this Badge.
        :rtype: str
        """
        return self._badge_class

    @badge_class.setter
    def badge_class(self, badge_class):
        """Sets the badge_class of this Badge.


        :param badge_class: The badge_class of this Badge.
        :type badge_class: str
        """

        self._badge_class = badge_class

    @property
    def issuer(self):
        """Gets the issuer of this Badge.


        :return: The issuer of this Badge.
        :rtype: str
        """
        return self._issuer

    @issuer.setter
    def issuer(self, issuer):
        """Sets the issuer of this Badge.


        :param issuer: The issuer of this Badge.
        :type issuer: str
        """

        self._issuer = issuer

    @property
    def image(self):
        """Gets the image of this Badge.


        :return: The image of this Badge.
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this Badge.


        :param image: The image of this Badge.
        :type image: str
        """

        self._image = image

    @property
    def recipient(self):
        """Gets the recipient of this Badge.


        :return: The recipient of this Badge.
        :rtype: BadgeRecipient
        """
        return self._recipient

    @recipient.setter
    def recipient(self, recipient):
        """Sets the recipient of this Badge.


        :param recipient: The recipient of this Badge.
        :type recipient: BadgeRecipient
        """

        self._recipient = recipient

    @property
    def issued_on(self):
        """Gets the issued_on of this Badge.


        :return: The issued_on of this Badge.
        :rtype: datetime
        """
        return self._issued_on

    @issued_on.setter
    def issued_on(self, issued_on):
        """Sets the issued_on of this Badge.


        :param issued_on: The issued_on of this Badge.
        :type issued_on: datetime
        """

        self._issued_on = issued_on
