# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Commands(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, commands: List[str]=[]):
        """Commands - a model defined in OpenAPI

        :param commands: The commands of this Commands.
        """
        self.openapi_types = {
            'commands': List[str]
        }

        self.attribute_map = {
            'commands': 'commands'
        }

        self._commands = commands

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Commands':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Commands of this Commands.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def commands(self):
        """Gets the commands of this Commands.


        :return: The commands of this Commands.
        :rtype: List[str]
        """
        return self._commands

    @commands.setter
    def commands(self, commands):
        """Sets the commands of this Commands.


        :param commands: The commands of this Commands.
        :type commands: List[str]
        """

        self._commands = commands
