# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CredsString(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, variable: str=None):
        """CredsString - a model defined in OpenAPI

        :param id: The id of this CredsString.
        :param variable: The variable of this CredsString.
        """
        self.openapi_types = {
            'id': str,
            'variable': str
        }

        self.attribute_map = {
            'id': 'id',
            'variable': 'variable'
        }

        self._id = id
        self._variable = variable

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CredsString':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Creds_string of this CredsString.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this CredsString.


        :return: The id of this CredsString.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CredsString.


        :param id: The id of this CredsString.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def variable(self):
        """Gets the variable of this CredsString.


        :return: The variable of this CredsString.
        :rtype: str
        """
        return self._variable

    @variable.setter
    def variable(self, variable):
        """Sets the variable of this CredsString.


        :param variable: The variable of this CredsString.
        :type variable: str
        """

        self._variable = variable
