# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, build_url: str=None):
        """InlineResponse2001 - a model defined in OpenAPI

        :param build_url: The build_url of this InlineResponse2001.
        """
        self.openapi_types = {
            'build_url': str
        }

        self.attribute_map = {
            'build_url': 'build_url'
        }

        self._build_url = build_url

    @classmethod
    def from_dict(cls, dikt: dict) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The inline_response_200_1 of this InlineResponse2001.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def build_url(self):
        """Gets the build_url of this InlineResponse2001.


        :return: The build_url of this InlineResponse2001.
        :rtype: str
        """
        return self._build_url

    @build_url.setter
    def build_url(self, build_url):
        """Sets the build_url of this InlineResponse2001.


        :param build_url: The build_url of this InlineResponse2001.
        :type build_url: str
        """

        self._build_url = build_url
