# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class InlineObject(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, repo: str=None):
        """InlineObject - a model defined in OpenAPI

        :param repo: The repo of this InlineObject.
        """
        self.openapi_types = {
            'repo': str
        }

        self.attribute_map = {
            'repo': 'repo'
        }

        self._repo = repo

    @classmethod
    def from_dict(cls, dikt: dict) -> 'InlineObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The inline_object of this InlineObject.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def repo(self):
        """Gets the repo of this InlineObject.

        URL of the upstream repo

        :return: The repo of this InlineObject.
        :rtype: str
        """
        return self._repo

    @repo.setter
    def repo(self, repo):
        """Sets the repo of this InlineObject.

        URL of the upstream repo

        :param repo: The repo of this InlineObject.
        :type repo: str
        """

        self._repo = repo
