# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server.models.je_pl_jenkinsfile_pipeline_config import JePLJenkinsfilePipelineConfig
from openapi_server.models.je_pl_jenkinsfile_when import JePLJenkinsfileWhen
from openapi_server import util


class JePLJenkinsfileStages(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, when: JePLJenkinsfileWhen=None, pipeline_config: JePLJenkinsfilePipelineConfig=None):
        """JePLJenkinsfileStages - a model defined in OpenAPI

        :param when: The when of this JePLJenkinsfileStages.
        :param pipeline_config: The pipeline_config of this JePLJenkinsfileStages.
        """
        self.openapi_types = {
            'when': JePLJenkinsfileWhen,
            'pipeline_config': JePLJenkinsfilePipelineConfig
        }

        self.attribute_map = {
            'when': 'when',
            'pipeline_config': 'pipeline_config'
        }

        self._when = when
        self._pipeline_config = pipeline_config

    @classmethod
    def from_dict(cls, dikt: dict) -> 'JePLJenkinsfileStages':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The JePL_jenkinsfile_stages of this JePLJenkinsfileStages.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def when(self):
        """Gets the when of this JePLJenkinsfileStages.


        :return: The when of this JePLJenkinsfileStages.
        :rtype: JePLJenkinsfileWhen
        """
        return self._when

    @when.setter
    def when(self, when):
        """Sets the when of this JePLJenkinsfileStages.


        :param when: The when of this JePLJenkinsfileStages.
        :type when: JePLJenkinsfileWhen
        """

        self._when = when

    @property
    def pipeline_config(self):
        """Gets the pipeline_config of this JePLJenkinsfileStages.


        :return: The pipeline_config of this JePLJenkinsfileStages.
        :rtype: JePLJenkinsfilePipelineConfig
        """
        return self._pipeline_config

    @pipeline_config.setter
    def pipeline_config(self, pipeline_config):
        """Sets the pipeline_config of this JePLJenkinsfileStages.


        :param pipeline_config: The pipeline_config of this JePLJenkinsfileStages.
        :type pipeline_config: JePLJenkinsfilePipelineConfig
        """

        self._pipeline_config = pipeline_config
