# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Repository(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, repo_id: str=None, repo_url: str=None, branch: str=None):
        """Repository - a model defined in OpenAPI

        :param repo_id: The repo_id of this Repository.
        :param repo_url: The repo_url of this Repository.
        :param branch: The branch of this Repository.
        """
        self.openapi_types = {
            'repo_id': str,
            'repo_url': str,
            'branch': str
        }

        self.attribute_map = {
            'repo_id': 'repo_id',
            'repo_url': 'repo_url',
            'branch': 'branch'
        }

        self._repo_id = repo_id
        self._repo_url = repo_url
        self._branch = branch

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Repository':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Repository of this Repository.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def repo_id(self):
        """Gets the repo_id of this Repository.


        :return: The repo_id of this Repository.
        :rtype: str
        """
        return self._repo_id

    @repo_id.setter
    def repo_id(self, repo_id):
        """Sets the repo_id of this Repository.


        :param repo_id: The repo_id of this Repository.
        :type repo_id: str
        """

        self._repo_id = repo_id

    @property
    def repo_url(self):
        """Gets the repo_url of this Repository.


        :return: The repo_url of this Repository.
        :rtype: str
        """
        return self._repo_url

    @repo_url.setter
    def repo_url(self, repo_url):
        """Sets the repo_url of this Repository.


        :param repo_url: The repo_url of this Repository.
        :type repo_url: str
        """

        self._repo_url = repo_url

    @property
    def branch(self):
        """Gets the branch of this Repository.


        :return: The branch of this Repository.
        :rtype: str
        """
        return self._branch

    @branch.setter
    def branch(self, branch):
        """Sets the branch of this Repository.


        :param branch: The branch of this Repository.
        :type branch: str
        """

        self._branch = branch
